### ISSUE TITLE
add_names out of range [CAT 5.0]

### ISSUE THREAD

**Issue by PierreFoucault** [MGXlab/CAT_pack#115]
Hi all,

I've been getting a similar error to 
[https://github.com/MGXlab/CAT_pack/issues/32](url)
when running cat add_names to get the contig2classification.txt file using CAT 5.3 GTDB prepared (20231120_CAT_gtdb)

here's the latest output: 
# CAT v5.3.
[2024-03-13 17:07:02] Loading file ./20231120_CAT_gtdb/tax/nodes.dmp.
[2024-03-13 17:07:02] Loading file ./20231120_CAT_gtdb/tax/names.dmp.
Traceback (most recent call last):
  File "/mnt/beegfs/pfoucault/conda_envs/myCAT-env/bin/CAT", line 87, in <module>
    main()
  File "/mnt/beegfs/pfoucault/conda_envs/myCAT-env/bin/CAT", line 73, in main
    add_names.run()
  File "/mnt/beegfs/pfoucault/conda_envs/myCAT-env/share/cat-5.3-0/CAT_pack/add_names.py", line 79, in run
    taxid2name = tax.import_names(args.names_dmp, args.log_file, args.quiet)
  File "/mnt/beegfs/pfoucault/conda_envs/myCAT-env/share/cat-5.3-0/CAT_pack/tax.py", line 39, in import_names
    if line[6] == "scientific name":
IndexError: list index out of range

Has anyone encountered the same error ? 
thx !

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi!

I have pushed a fix for this, in future releases of the CAT pack you will be able to use the `add_names` utility with the GTDB database as well. @thauptfeld is right that the names are already included in the lineage of GTDB so this may be a bit redundant, however the `add_names` script also allows you to restructure the output files, with for example all classifications of the same rank in the same column, with or without scores, etc., In general generating the same output files for NCBI nr and GTDB seems useful for downstream analyses.

There is one "but", which is that for this to work I also had to push a fix for the GTDB download script. So the fix will work only for future _database releases_ as well. @thauptfeld will generate a new database with the next release (v6.0.2) to accommodate this.

Best wishes,

Bastiaan
